#!/bin/bash

# Make image file of optical drive

# TODO: Add mount check

ROOT_UID=0      # Only users with $UID 0 have root privileges
E_ROOT=86       # Root exit error
E_BLOCKSIZE=87  # Source blocksize error
E_VOLUMESIZE=88 # Source volume size error

SOURCE_DRIVE=/dev/sr0

# Do not run as root, of course.
if [ "$UID" -eq "$ROOT_UID" ]
then
  echo "Must not be root to run this script."
  exit $E_ROOT
fi

if [ -z $1 ]
then
    IMAGE_FILE=${HOME}/`date +%Y%m%d%H%M%S`.iso
else
    IMAGE_FILE=${HOME}/$1
fi

BLOCK_SIZE=`isoinfo -d -i $SOURCE_DRIVE | grep "^Logical block size is:" | cut -d " " -f 5`
if test "$BLOCK_SIZE" = ""; then
    echo Source blocksize error
    exit $E_BLOCKSIZE
fi

VOLUME_SIZE=`isoinfo -d -i $device | grep "^Volume size is:" | cut -d " " -f 4`
if test "$VOLUME_SIZE" = ""; then
    echo Source volume size error
    exit $E_VOLUMESIZE
fi

dd if=${SOURCE_DRIVE} of=${IMAGE_FILE} bs=${BLOCK_SIZE} count=${VOLUME_SIZE}

echo ISO image file created: ${IMAGE_FILE}
